import Head from "next/head";
// import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "antd";

import { Principal as DashboardLayout } from "@/layout/dashboard";
import { ReactElement } from "react";
import { useDispatch, useSelector } from "react-redux";
import { decrement, increment } from "@/store/slices/counterSlice";
import { RootState } from "@/store";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const count = useSelector((state: RootState) => state.counter.value);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button type="primary">Button</Button>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
      
          <h1>Contador: {count}</h1>
          <button onClick={() => dispatch(increment())}>+</button>
          <button onClick={() => dispatch(decrement())}>-</button>
      </div>
    </>
  );
}

Home.getLayout = (page:ReactElement) => <DashboardLayout title="home">{page}</DashboardLayout>;
