import React, { ReactElement, useState } from 'react';
import {
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    TableOutlined,
    ProductOutlined,
} from '@ant-design/icons';

interface Item {
    key: string;
    // o el tipo adecuado para `key`
    // otros campos que puedas tener
}

import { Button, Layout, Menu, MenuProps, theme } from 'antd';
import { useRouter } from 'next/router';
import Head from 'next/head';
const { Header, Content, Sider } = Layout;
type MenuItem = Exclude<NonNullable<MenuProps["items"]>[number], null | undefined> & {
    path: string;
    label: string;
};
const items: MenuItem[] = [
    {
        key: 0,
        icon: <TableOutlined />,
        label: 'Tabla Dinamica',
        path: '/tablaDinamica',
    },
    {
        key: 1,
        icon: <ProductOutlined />,
        label: 'Productos',
        path: '/productos',

    },
]
interface DashboardLayoutProps {
    title: string;  // Título que se pasará como prop
    children: ReactElement;  // El contenido que se pasará como prop (la página)
  }

export const Principal = ({ children, title }: DashboardLayoutProps) => {
    const router = useRouter();
    const [collapsed, setCollapsed] = useState(false);
    const [titleScreen, setTitleScreen] = useState(0);
    const [selectedKeys, setSelectedKeys] = useState("");

    const getValues = (item: Item) => {
        const path = items.filter(element => element.key == item?.key);
        console.log(item, path)
        
        const selectedKey = path[0]?.key !== undefined ? `${path[0]?.key}` : "";
        setSelectedKeys(selectedKey);
        router.push(path[0].path)
    };

    const {
        token: { colorBgContainer, borderRadiusLG },
    } = theme.useToken();
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Sider trigger={null} collapsible collapsed={collapsed}>
                    <div className="demo-logo-vertical" />
                    <Menu
                        theme="dark"
                        mode="inline"
                        selectedKeys={[`${selectedKeys}`]}
                        defaultSelectedKeys={['0']}
                        onClick={(e) => { setTitleScreen(parseInt(e.key)); getValues(e) }}
                        items={items}
                    />
                </Sider>
                <Layout>
                    <Header style={{ padding: 0, background: colorBgContainer }}>
                        <Button
                            type="text"
                            icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
                            onClick={() => setCollapsed(!collapsed)}
                            style={{
                                fontSize: '16px',
                                width: 64,
                                height: 64,
                            }}
                        />
                        {items[titleScreen] && items[titleScreen]?.label}

                    </Header>
                    <Content
                        style={{
                            margin: '24px 16px',
                            padding: 24,
                            minHeight: 280,
                            background: colorBgContainer,
                            borderRadius: borderRadiusLG,
                        }}
                    >
                        {children}
                    </Content>
                </Layout>
            </Layout>
        </>
    );
}
